/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * @author Patrick Lennon
 */

public class Euler2 {

    public static void main(String[] args) {
        int previous = 0;
        int curr = 1;
        long sum = 0;
        int counter = 0;

        while(curr < 4000000){
            if(counter == 0){ //first number, no previous number to add to it
                previous = curr;
                curr += curr;
            }
            else{
                int temp = curr;
                curr += previous;
                previous = temp;
            }
            if(curr%2==0){
                sum += curr;
            }
            counter += 1;
        }
        System.out.println(sum);
    }
}
